name: 04-using-actions

on:
  workflow_dispatch:

jobs:
  java_mavenrepo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with: 
          java-version: '17'
          distribution: 'temurin'
      - name: setup maven
        uses: actions/checkout@v3
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - name: upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: staging
#     - name: Run unit test
#        run: npm run test
#       working-directory: 04-using-actions/maven-app
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
         version: '20.X'
         
